### ISSUE TITLE
Automated mining excavator not working /MeanCloud__Mining

### ISSUE THREAD

**Issue by TomT15** [psouza4/MeanCloud_7DtD#1]
Which file? MeanCloud__Mining
Description: When putting the excavator down one of two things happen. First, it is treated as an inworld item and does not open the container. 2) The item is acting like it is doing anything. im pretty sure something is acting up but not quite sure since im new.

**Comment by psouza4** [comment]
It takes quite some time for the excavator to burrow and produce loot.  Do not pick it up right away.  This is normal behavior.  See the images at the forum for examples.
